---
- name: Download files
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Download Python installer
      get_url: 
        url: https://www.python.org/ftp/python/3.13.5/python-3.13.5-macos11.pkg
        dest: /Users/cjain/Downloads/python-3.13.5-macos11.pkg
        mode: '0777'



